MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNVad"
  WEIGHT: "catalog://Caffe2Detectron/COCO/35857197/e2e_faster_rcnn_R-50-C4_1x"
  ROI_BOX_HEAD:
    PREDICTOR: "FastRCNNPredictorVad"
DATASETS:
  TEST: ("coco_2014_minival",)
